import React,{useState} from 'react';
import {ArrowRight,Eye,EyeOff,Lock,LockKeyhole,UserRound} from 'lucide-react';
import {useAuth} from '../../context/AuthContext';
export function AuthModal(){
 const {currentUser,isApproved,loading,error,setupRequired,login,register,logout,refresh}=useAuth();
 const [mode,setMode]=useState('login'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[showPassword,setShowPassword]=useState(false);
 const registration=mode==='register';
 const initialSetup=registration&&setupRequired;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const d=Object.fromEntries(new FormData(e.currentTarget));try{const r=registration?await register(d):await login(d.username,d.password);if(!r.success)setMessage(r.message);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(isApproved)return null;
 return <div className="auth-page auth-visual-page"><div className="auth-visual" aria-hidden="true"/><main className="auth-form-side"><section className="auth-card"><h1 className="auth-title">Beykoz Sohbetleri</h1>
 {loading?<p>Yükleniyor…</p>:error?<p role="alert">{error}</p>:currentUser?<div className="auth-pending"><Lock/><h2>Üyelik onayı bekleniyor</h2><p>{currentUser.name}, başvurunuz alındı. Yönetici onayından sonra sohbetlere erişebilirsiniz.</p><button onClick={()=>refresh()}>Başvuru durumunu kontrol et</button><button className="secondary" onClick={logout}>Çıkış yap</button></div>:<>
 {registration&&<p className="auth-register-note">{setupRequired?'İlk hesap yönetici hesabınız olacak.':'Bilgilerinizi gönderin. Kullanıcı adınız ve şifreniz yönetici onayından sonra oluşturulacaktır.'}</p>}
 <form onSubmit={submit}>{initialSetup?<><label>Ad soyad<input name="name" required autoComplete="name"/></label><label>Kullanıcı adı<input name="username" type="text" required autoComplete="username" autoCapitalize="none" spellCheck={false} minLength={3} maxLength={32} pattern="[a-zA-Z0-9_.-]{3,32}"/></label><label>Şifre<input name="password" type="password" required minLength={10} maxLength={256} autoComplete="new-password"/></label><small>Kullanıcı adı 3–32 karakter, şifre en az 10 karakter olmalıdır.</small></>:registration?<><label>Ad Soyad<input name="name" required autoComplete="name" maxLength={160}/></label><label>Doğum Tarihi<input name="birthDate" type="date" required autoComplete="bday" max={new Date().toISOString().slice(0,10)}/></label><label>Telefon Numarası<input name="phone" type="tel" required autoComplete="tel" inputMode="tel" maxLength={30} defaultValue="+905" placeholder="+90 5__ ___ __ __" aria-describedby="phone-country-hint"/><small id="phone-country-hint">Ülke kodunu gerektiğinde değiştirebilirsiniz.</small></label></>:<><label>Kullanıcı adı<div className="auth-input-wrap"><UserRound size={18}/><input name="username" type="text" required autoComplete="username" autoCapitalize="none" spellCheck={false} maxLength={32} placeholder="Kullanıcı adınız"/></div></label><label>Şifre<div className="auth-input-wrap"><LockKeyhole size={18}/><input name="password" type={showPassword?'text':'password'} required maxLength={256} autoComplete="current-password" placeholder="••••••••"/><button className="auth-password-toggle" type="button" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'Şifreyi gizle':'Şifreyi göster'}>{showPassword?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label></>}{message&&<p role="alert" className="form-error">{message}</p>}<button className="auth-submit" disabled={busy} type="submit">{busy?'Lütfen bekleyin…':registration?'Başvuru gönder':'Giriş yap'} <ArrowRight size={16}/></button></form><p className="auth-switch-line">{registration?'Zaten hesabınız var mı?':'Hesabınız yok mu?'} <button type="button" className="auth-switch" onClick={()=>{setMode(registration?'login':'register');setMessage('');}}>{registration?'Giriş yapın':'Hesap oluştur'}</button></p></>}
 </section></main></div>;
}
